### PR TITLE
Use new location for terminals

### PR DESCRIPTION
**Pull request by benoitf**
it's under terminal menu

Will allow to switch to theia 0.3.17

Change-Id: I54d56fa2514bf62c95a2b3730336db49870122aa
Signed-off-by: Florent Benoit <fbenoit@redhat.com>

### CODE REVIEW

**Comment by AndrienkoAleksandr** [comment]
@benoitf yarn.lock should be changed  after changing dependency.

**Comment by benoitf** [comment]
@AndrienkoAleksandr yes but I was planning another PR as yarn.lock has also an issue with the removed event-stream package

**Comment by AndrienkoAleksandr** [comment]
@benoitf Ok. LGTM.

**Comment by benoitf** [comment]
this line https://github.com/eclipse/che-theia-terminal-extension/blob/master/yarn.lock#L3717
https://blog.npmjs.org/post/180565383195/details-about-the-event-stream-incident

**Pull request merged**
